from django.urls import path
from .views import (
    CategoryListAPIView,
    ReviewAPIView,
    get_products,
    related_products,
    dashboard_products,
    dashboard_new_arrivals,
    dashboard_offers,
    dashboard_reviews,
    dashboard_orders,
    dashboard_categories,
    add_category,
    edit_category,
    delete_category,
    create_order,
    order_detail,
    order_detail_view,
    order_delete_view,
    get_orders,
)

from . import views

app_name = 'products'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', dashboard_products, name='dashboard_root'),
    path('dashboard/products/', dashboard_products, name='dashboard_products'),
    path('dashboard/new-arrivals/', dashboard_new_arrivals, name='dashboard_new_arrivals'),
    path('dashboard/offers/', dashboard_offers, name='dashboard_offers'),
    path('dashboard/reviews/', dashboard_reviews, name='dashboard_reviews'),
    path('dashboard/offer-reviews/', views.dashboard_offer_reviews, name='dashboard_offer_reviews'),
    path('dashboard/orders/', dashboard_orders, name='dashboard_orders'),
    path('dashboard/order/<int:pk>/', order_detail_view, name='dashboard_order_detail'),
    path('<int:pk>/details/', views.product_details, name='product_details'),
    path('add/', views.add_product, name='add_product'),
    path('<int:pk>/delete/', views.delete_product, name='delete_product'),
    path('<int:pk>/edit/', views.edit_product, name='edit_product'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('api/products/', get_products),
    path('products/', get_products),
    path('add-offer/', views.add_offer, name='add_offer'),
    path('edit-offer/<int:pk>/', views.edit_offer, name='edit_offer'),
    path('delete-offer/<int:pk>/', views.delete_offer, name='delete_offer'),
    path('offers/', views.offers_list, name='offers_list'),
    path('offer/<int:pk>/', views.offer_details, name='offer_details'),
    path('review/<int:pk>/', views.review_detail, name='review_detail'),
    path('offer-review/<int:pk>/', views.offer_review_detail, name='offer_review_detail'),
    path('api/offers/<int:pk>/', views.offer_detail, name='offer_detail_api'),
    path('api/offers/<int:offer_id>/reviews/', views.OfferReviewAPIView.as_view()),
    path('new-arrivals/', views.new_arrivals_list, name='new_arrivals_list'),
    path('add-new-arrival/', views.add_new_product, name='add_new_product'),
    path('edit-new-arrival/<int:pk>/', views.edit_new_product, name='edit_new_product'),
    path('new-product/<int:pk>/', views.new_product_details, name='new_product_details'),
    path('delete-new-arrival/<int:pk>/', views.delete_new_product, name='delete_new_product'),
    path('api/categories/', CategoryListAPIView.as_view()),
    path('api/products/<int:pk>/', views.product_detail),
    path("api/products/<int:product_id>/reviews/", ReviewAPIView.as_view()),
    path('products/<int:pk>/related/', related_products),
    # Order endpoints
    path('orders/', create_order, name='orders_create'),
    path('api/orders/', get_orders, name='get_orders'),
    path('api/orders/create/', create_order, name='create_order'),
    path('api/orders/<int:pk>/', order_detail, name='order_detail_api'),
    path('dashboard/order/<int:pk>/delete/', order_delete_view, name='dashboard_order_delete'),
    path('dashboard/categories/', dashboard_categories, name='dashboard_categories'),
    path('dashboard/categories/add/', add_category, name='add_category'),
    path('dashboard/categories/<int:pk>/edit/', edit_category, name='edit_category'),
    path('dashboard/categories/<int:pk>/delete/', delete_category, name='delete_category'),
]