# Generated by Django 6.0.7 on 2026-08-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='new_arrivals/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='new_arrivals/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='new_arrivals/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='new_arrivals/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='new_arrivals/')),
                ('price_details', models.TextField(blank=True, null=True)),
                ('specs', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
