# Generated by Django 6.0.7 on 2026-08-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(db_index=True, default='', editable=False, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
