# Generated by Django 6.0.7 on 2026-08-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
