# Generated by Django 6.0.5 on 2026-06-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='subject',
        ),
    ]
