# Generated by Django 6.0.6 on 2026-06-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_review_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='newarrival',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newarrival',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='new_arrivals/'),
        ),
        migrations.AddField(
            model_name='newarrival',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='new_arrivals/'),
        ),
        migrations.AddField(
            model_name='newarrival',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='new_arrivals/'),
        ),
        migrations.AddField(
            model_name='newarrival',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='new_arrivals/'),
        ),
        migrations.AddField(
            model_name='newarrival',
            name='price_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newarrival',
            name='specs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='price_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='specs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
