# Generated by Django 6.0.6 on 2026-06-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_newarrival_features_newarrival_image_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_details',
            new_name='more_details',
        ),
    ]
