# Generated by Django 6.0.6 on 2026-06-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_offer_stock_offerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
