# Generated by Django 6.0.6 on 2026-06-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_offer_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerreview',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
