# Generated by Django 6.0.6 on 2026-08-03 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_order_stock_deducted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newarrival',
            old_name='price_details',
            new_name='more_details',
        ),
        migrations.RemoveField(
            model_name='newarrival',
            name='title',
        ),
        migrations.AddField(
            model_name='newarrival',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_arrivals', to='products.category'),
        ),
        migrations.AddField(
            model_name='newarrival',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newarrival',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newarrival',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='newarrival',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
