# Generated by Django 6.0.6 on 2026-08-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_price_details_newarrival_more_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newarrival',
            old_name='more_details',
            new_name='price_details',
        ),
        migrations.RenameField(
            model_name='newarrival',
            old_name='name',
            new_name='title',
        ),
    ]
