# Generated by Django 6.0.6 on 2026-08-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_more_details_newarrival_price_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newarrival',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newarrival',
            name='description',
        ),
        migrations.RemoveField(
            model_name='newarrival',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='newarrival',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured_new_arrival',
            field=models.BooleanField(default=False, help_text='المنتج المميز اللي يظهر في قسم New Arrivals - منتج واحد بس ينفع يكون True'),
        ),
        migrations.AlterField(
            model_name='newarrival',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
