# Generated by Django 6.0.7 on 2026-08-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_migrate_new_arrivals_to_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewArrival',
        ),
    ]
