# Generated by Django 6.0.7 on 2026-08-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_delete_newarrival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerreview',
            name='offer',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='OfferReview',
        ),
    ]
