# Generated by Django 6.0.7 on 2026-08-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_offerreview_offer_delete_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
