FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# نحفظ نسخة من الـmedia داخل الـDocker image
# عشان Railway Volume مش هيغطي النسخة دي
RUN cp -a /app/media /app/media_initial

# إنشاء المستخدم
RUN useradd -m appuser \
    && chown -R appuser:appuser /app

# entrypoint
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8000

ENTRYPOINT ["/entrypoint.sh"]